global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: "rising_helpdesk_api"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["api:8001"]
        labels:
          application: "rising_helpdesk"
